name: lego
base: core22
version: 'v4.15.0'
summary: A Let's Encrypt client.
license: Apache-2.0
description: |
  LEGO is a Let's Encrypt client and ACME library written in Go.

  The LEGO snap makes it easy to install and use LEGO on any Linux distribution that supports snaps.

  Usage:

  `sudo snap install lego`

  `sudo snap connect lego:dot-lego`
  `lego --email="you@example.com" --domains="example.com" --path=/var/snap/lego/common/.lego --server=https://acme-staging-v02.api.letsencrypt.org/directory --http --http.port :8080 run`

  Note: The LEGO snap can only write to the `/var/snap/lego/common/.lego` directory.

source-code: https://github.com/go-acme/lego
issues: https://github.com/gruyaume/lego-snap/issues

grade: stable
confinement: strict

apps:
  lego:
    command: bin/lego
    plugs:
      - network-bind

parts:
  lego:
    plugin: go
    source: https://github.com/go-acme/lego
    source-type: git
    source-tag: v4.15.0
    build-snaps:
      - go/1.21/stable
    build-environment:
      - GO111MODULE: "on"
